Tbranch
pirates14/BERT pull request #6
Opened 2021-11-09 01:17 UTC by hale-in

@eubinecto

2021-11-10 12:51 UTC, eubinecto requested changes
가상환경은 깃에다가 업로드하면 안됩니다!!! 얼른 제거해주세요!

2021-11-14 12:18 UTC, hale-in commented
C:\Users\user\PycharmProjects\sourscoring\venv\Scripts>git rm -r --cached venv
fatal: pathspec 'venv' did not match any files

gitignore에 venv를 넣었더니 이렇게 뜹니다. 이제는 merge가 가능할까요?

2021-11-17 06:43 UTC, eubinecto commented on sourcescoring/examples/explore_data_crawling.py
> +print('\n크롤링을 시작합니다.')
크롤링 ->  스크레이핑 (scraping)

2021-11-17 06:50 UTC, eubinecto approved these changes

2021-11-17 06:50 UTC, merged