Issue 7
pirates14/BERT pull request #9
Opened 2021-11-22 06:53 UTC by eeunn

2021-11-22 07:10 UTC, eubinecto requested changes

2021-11-22 07:10 UTC, eubinecto commented on main_train.py
> +    inputs = InputsBuilder(tokenizer, sentences=sentences, max_len=100)
여기 밑에 부분 `config`을 사용해서 하이퍼파라미터를 접근하는 방식으로 변경해주세요! ㅎㅎ

2021-11-22 07:12 UTC, eubinecto requested changes

2021-11-22 07:12 UTC, eubinecto commented on BERT/tensors.py
> +        return inputs.to('cpu')
이 부분은 cpu에 올리지 말아주세요!
그냥 `inputs` 을 그대로 출력하면 됩니다 ㅎㅎ

2021-11-22 07:16 UTC, eubinecto commented on BERT/tensors.py
> +        anm_targets_p = pad_sequences(anm_targets, maxlen=self.max_len, padding='post')
padding으로 사용되는 정수가 아마도 0일 텐데,  이게 실제로  `[PAD]` 토큰의 정수 인코딩에 대응하는지 확인부탁드립니다!

2021-11-22 07:34 UTC, eeunn commented on BERT/tensors.py
> +        anm_targets_p = pad_sequences(anm_targets, maxlen=self.max_len, padding='post')
ner, anm 둘 다 O와 겹칩니다. 수정할 생각인데 어떻게 수정해야 될 지 모르겠습니다.

2021-11-22 09:23 UTC, eubinecto commented on BERT/tensors.py
> +        anm_targets_p = pad_sequences(anm_targets, maxlen=self.max_len, padding='post')
아 제가 오해를 했었네요~!! 그 둘이 겹치는 것은 괜찮아요. 다만:
```
pad_sequences(..., value=NER_CLASSES.index("O")
pad_sequences(..., value=ANM_CLASSES.index("O")
```
이렇게 패딩의 값으로 무엇을 사용하는지 정확하게 표기하는 것이 좋을듯해요!

2021-11-22 10:34 UTC, eubinecto requested changes

2021-11-22 10:34 UTC, eubinecto commented on BERT/tensors.py
> +        encoded = self.tokenizer(text=sent2tokens,
여기 부분 변경이 필요해요. 지금 처럼 진행을 하면 이미 토큰화가 된 것을 또 토큰화를 하더군요. - 이건  알려진 이슈이고, 당분간 고쳐지기는 힘들 것 같습니다. 
고로,  이전에 했던 것처럼 다음과 같이 `input_ids`, `token_type_ids`, `attention_mask`를 일일히 만들어주세요:
https://github.com/pirates14/BERT/blob/95054de054314aedbd5818541aa37b8f4396e585/examples/explore_%20tokenizing_pretokenized.py#L7-L22

2021-11-26 17:01 UTC, eubinecto approved these changes

2021-11-26 17:02 UTC, eubinecto commented
LGTM,  as of right now

2021-11-26 17:02 UTC, merged